apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: demo
  labels:
    app: logstash-demo
spec:
  version: 8.3.2
  nodeSets:
    - name: default
      count: 1
      config:
        node.store.allow_mmap: false