name: Docs Preview Link

on:
  pull_request_target:
    types: [opened, synchronize]
    paths:
      - docs/**
      - docsk8s/**
jobs:
  docs-preview-link:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - id: wait-for-status
        uses: autotelic/action-wait-for-status-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          owner: elastic
          # when running with on: pull_request_target we get the PR base ref by default
          ref: ${{ github.event.pull_request.head.sha }}
          statusName: "buildkite/docs-build-pr"
          # https://elasticsearch-ci.elastic.co/job/elastic+logstash+pull-request+build-docs
          # usually finishes in ~ 20 minutes
          timeoutSeconds: 900
          intervalSeconds: 30
      - name: Add Docs Preview link in PR Comment
        if: steps.wait-for-status.outputs.state == 'success'
        uses: thollander/actions-comment-pull-request@v1
        with:
          message: |
            :page_with_curl: **DOCS PREVIEW** :sparkles: https://logstash_bk_${{ github.event.number }}.docs-preview.app.elstc.co/diff
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
