name: Scan for vulnerabilities

on:
  pull_request:
    types: [opened, synchronize]
  workflow_dispatch:

jobs:
  scan_image:
    runs-on: ubuntu-latest
    steps: 
      - name: checkout repo content
        uses: actions/checkout@v6
      - name: build tar distribution
        run: ./gradlew clean assembleTarDistribution
      - run: mkdir scan
      - run: tar -zxf ../build/logstash-*.tar.gz
        working-directory: ./scan
      - name: scan image
        uses: anchore/scan-action@0d444ed77d83ee2ba7f5ced0d90d640a1281d762 # v7.3.0
        with:
          path: "./scan"
          fail-build: true
          severity-cutoff: critical
          output-format: table
