name: Scan for vulnerabilities

on:
  pull_request_target:
    types: [opened, synchronize]
  workflow_dispatch:

jobs:
  scan_image:
    runs-on: ubuntu-latest
    steps: 
      - name: checkout repo content
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: ./gradlew clean assembleTarDistribution
      - run: ls -lha
      - run: mkdir scan
      - run: tar -zxf ../build/logstash-*.tar.gz
        working-directory: ./scan
      - run: ls -lha scan
      - name: Scan image
        uses: anchore/scan-action@v3
        with:
          path: "./scan"
          fail-build: true
          severity-cutoff: critical
